apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        #image: chitransh1/myrepo:2.0
        image: nginxcvghjklkjhgcvghjkijhgv
        ports:
        - containerPort: 5000

---

apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: postsync-job-success
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - |
              echo "This is Post-Sync"
      restartPolicy: Never
