apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: chitransh1/myrepo:2.0
        ports:
        - containerPort: 5000

---

apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: postsync-job-success
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - |
              failed_pods=$(kubectl get pods -n myapp -l app=myapp -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}' | grep False)

              if [[ -n "$failed_pods" ]]; then
                echo "One or more pods are down: $failed_pods"
              else
                echo "All pods are running successfully."
              fi
      restartPolicy: Never
